# Generated by Django 4.1.2 on 2022-11-21 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mail_address',
            new_name='email_address',
        ),
    ]
